<?xml version="1.0"?>
<package format="3">
  <name>depthai_ros_driver</name>
  <version>2.12.2</version>
  <description>Minimal DepthAI ROS2 driver for image/depth/pointcloud pipelines.</description>
  <maintainer email="dev@luxonis.com">DepthAI ROS Maintainers</maintainer>
  <author>Adam Serafin</author>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>ros_environment</build_depend>
  <depend>ament_cmake_auto</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>rclcpp_components</depend>
  <depend>lifecycle_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>cv_bridge</depend>
  <depend>camera_info_manager</depend>
  <depend>libopencv-dev</depend>
  <depend>image_transport</depend>
  <depend>depthai</depend>
  <depend>depthai_bridge</depend>
  <depend>pluginlib</depend>
  <depend>diagnostic_updater</depend>
  <depend>diagnostic_msgs</depend>
  <depend>rii_common_utils</depend>
  <depend>ffmpeg_image_transport_msgs</depend>

  <exec_depend>depth_image_proc</exec_depend>
  <exec_depend>image_proc</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
