<?xml version="1.0"?>
<package format="3">
  <name>depthai_bridge</name>
  <version>2.12.2</version>
  <description>Minimal DepthAI bridge converters for ROS2 image streams.</description>
  <maintainer email="dev@luxonis.com">DepthAI ROS Maintainers</maintainer>

  <author>Adam Serafin</author>
  <author>Sachin Guruswamy</author>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>ros_environment</build_depend>
  <depend>rclcpp</depend>
  <depend>cv_bridge</depend>
  <depend>depthai</depend>
  <depend>libopencv-dev</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>ffmpeg_image_transport_msgs</depend>

  <export>
      <build_type>ament_cmake</build_type>
  </export>
</package>
