/**:
  ros__parameters:
    camera:
      i_pipeline_type: RGBD
      i_enable_ir: true
      i_enable_diagnostics: false
    rgb:
      i_publish_topic: true
      i_enable_preview: false
    stereo:
      i_publish_topic: true
      i_align_depth: true
      i_subpixel: true
