/**:
  ros__parameters:
    camera:
      i_pipeline_type: RGBD
      i_enable_diagnostics: false
    pipeline_gen:
      i_enable_sync: true
    rgb:
      i_synced: true
    stereo:
      i_align_depth: true
      i_subpixel: true
      i_synced: true
